Testes
alerj/legislaqui pull request #279
Opened 2020-11-03 18:32 UTC by ricardocamargo07

2020-11-06 18:59 UTC, BMasquio commented on resources/views/emails/proposal-changed.blade.php
> +<a href="{{route('proposal.show', ['id' => $proposal->id])}}">Link</a
Acho que vc apagou sem querer esse fechamento de tag

2020-11-06 23:09 UTC, ricardocamargo07 commented on resources/views/emails/proposal-changed.blade.php
> +<a href="{{route('proposal.show', ['id' => $proposal->id])}}">Link</a
Com certeza, vou alterar e coloco aqui de novo.

2021-03-05 19:01 UTC, ricardocamargo07 commented
@BMasquio

2021-03-15 16:59 UTC, BMasquio requested changes
Analisar a mudança do campo `proposal_state`

2021-03-15 16:59 UTC, BMasquio commented on resources/views/proposals/index.blade.php
> +                    {{ Form::select('state', $states, $state ,['data-width'=>'100%','data-style'=>'form-control', 'data-live-search'=>'true', 'title'=>'Situação', 'name'=> 'proposal_state']) }}
Isso altera a função de busca. Da forma que está, todas as buscas serão feitas considerando TODAS as propostas. Teve algum motivo para mudar isso?

2021-03-15 18:14 UTC, closed without merging